version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tinyoutbox-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: orderdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: tinyoutbox-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pgdata: